# Use the official Debian Bullseye as the base image for amd64
FROM --platform=linux/amd64 debian:bullseye

# Set the environment variables for non-interactive installation
ENV DEBIAN_FRONTEND=noninteractive

# Update the package repository and install required dependencies
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    libssh2-1-dev \
    zlib1g-dev \
    gcc \
    binutils \
    libc6-dev \
    libfindbin-libs-perl \
    cmake \
    wget \
    python3.9 \
    python3.9-venv \
    python3.9-dev \
    python3-pip \
    python3-dev \
    tar \
    pkg-config \
    curl \
    libssh2-1 \
    zlib1g \
    libffi-dev \
    default-libmysqlclient-dev \
    libpq-dev \
    tini \
    git \
    openssh-client \
    corkscrew

# Create an app directory
RUN mkdir /app
WORKDIR /app

## --- GO --- ##
RUN wget https://golang.org/dl/go1.20.4.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.20.4.linux-amd64.tar.gz && \
    rm go1.20.4.linux-amd64.tar.gz

# Set Go environment variables
ENV PATH="/usr/local/go/bin:${PATH}"
ENV GOPROXY=https://goproxy.io,direct
ENV GOOS=linux
ENV GOARCH=amd64

# Copy go.mod and go.sum files first to leverage Docker cache
COPY go.mod go.sum ./
RUN go mod download

# Create directory for building libgit2
RUN mkdir -p /tmp/build && cd /tmp/build && \
    wget https://github.com/libgit2/libgit2/archive/refs/tags/v1.3.2.tar.gz -O - | tar -xz && \
    cd libgit2-1.3.2 && \
    mkdir build && cd build && \
    cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=/usr/local && \
    make -j install

# Set PKG_CONFIG_PATH so pkg-config can find libgit2.pc
ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

## --- Python --- #
# Create a symlink for python3.9 to python
RUN ln -s /usr/bin/python3.9 /usr/bin/python

# Upgrade pip and setuptools and install pipx
RUN python -m pip install --no-cache --upgrade pip setuptools pipx
RUN pipx install poetry
RUN pipx ensurepath

# Copy the rest of the application files
COPY . .

# Command to run when container starts
CMD ["bash"]
